[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Karl Rydberg", email = "kalle.rydberg02@gmail.com" }
]
requires-python = ">=3.13"
dependencies = ["uvicorn", "fastapi", "pandas", "sqlalchemy", "psycopg[binary]"]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"
